[package]
name = "vanessa"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
tonic = "0.13.1"
prost = "0.14.1"

[build-dependencies]
tonic-build = "0.13.1"